application: lunchere
version: dev
runtime: python27
api_version: 1
threadsafe: false

handlers:
# the admin is /_ah/spi, while the api is automatially set to /_ah/api/*
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /images
  static_dir: images
# - url: /
#  static_files: test.html
#  upload: test\.html
- url: /_ah/spi/.*
  script: lunchere.endpoints_application
- url: /.*
  script: lunchere.test # Please use the class name

libraries:
- name: pycrypto
  version: latest
