application: lunchere
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
# the admin is /_ah/spi, while the api is automatially set to /_ah/api/*
- url: /_ah/spi/.*
  script: services.endpoints_application

- url: /.*
  script: lunchere.test # Please use the class name

